---
# tasks file for role-mailcatcher
- name: Install required software
  apt: pkg={{ item }} state=latest
  with_items:
      - sqlite3
      - libsqlite3-dev
      - ruby-dev
      - rubygems
      
- name: Install Mailcatcher
  sudo: yes
  command: gem install mailcatcher --no-rdoc --no-ri creates=/usr/local/bin/mailcatcher
  notify:
    - Start Mailcatcher on boot
    - Stop Mailcatcher
    - Start Mailcatcher

- name: Create startup script for mailcatcher
  template: src=mailcatcher.j2 dest=/etc/init.d/mailcatcher mode=0755 force=no

- name: Ensure mailcatcher is running and starts on boot
  service: name=mailcatcher state=started enabled=true
