---
- name: Install required packages
  apt: pkg={{ item }} update_cache=yes
  sudo: yes
  with_items:
      - python-mysqldb
      - mysql-server
      - mysql-client
      
- name: Change MySQL config
  lineinfile:
    dest=/etc/mysql/my.cnf
    line="collation-server = utf8_unicode_ci"
    insertafter="^\[mysqld\]"
  sudo: yes
  notify: Restart MySQL

- name: Change MySQL config
  lineinfile:
    dest=/etc/mysql/my.cnf
    line="init-connect = 'SET NAMES utf8'"
    insertafter="^collation-server ="
  sudo: yes
  notify: Restart MySQL

- name: Change MySQL config
  lineinfile:
    dest=/etc/mysql/my.cnf
    line="character-set-server = utf8"
    insertafter="^init-connect ="
  sudo: yes
  notify: Restart MySQL

- name: Ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true
